### ISSUE TITLE
Showing validation message "You must enter a valid order id"

### ISSUE THREAD

**Issue by utsavsolanki** [pacocastillo/WC-Return-Products#1]
While click on "Return Order" button from myaccount section , A validation message 
"You must enter a valid order id"  throwing , There is a no any text field provided for enter the "Order Id"
Let me know , my wordpress version: 4.2.2

**Comment by pacocastillo** [comment]
Yes, this validation message is bad but this happen because you haven't selected any product from your order. I will change it. Thanks!!!
![captura de pantalla 2015-06-12 a las 19 09 24](https://cloud.githubusercontent.com/assets/3977317/8135306/9b7edfaa-1136-11e5-8ada-4cdd88674998.png)

**Comment by pacocastillo** [comment]
This validation message is only for debug and this happens when the input with the id of the order is removed from form (and this should not occur if you edit the form).

**Comment by pacocastillo** [comment]
You're right. Updated! Thanks!
